/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package grap.panel;

import grap.*;
import grap.dto.Link;
import grap.service.LinkService;
import java.util.Date;
import javax.swing.JOptionPane;
import org.springframework.context.ApplicationContext;

/**
 *
 * @author cz
 */
public class ModifyLinkPanel extends javax.swing.JPanel {

    private ApplicationContext ctx;
    private long id;

    /**
     * Creates new form addLinkPanel
     */
    public ModifyLinkPanel(ApplicationContext ctx, long linkId) {
        this.ctx = ctx;
        initComponents();
        initLink(linkId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        url = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        period = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sub = new javax.swing.JButton();
        cla = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        linkName = new javax.swing.JTextField();

        jLabel1.setText("url地址：");

        url.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlActionPerformed(evt);
            }
        });

        jLabel2.setText("扫描周期：");

        jLabel3.setText("秒");

        sub.setText("保存");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });

        cla.setText("取消");
        cla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claActionPerformed(evt);
            }
        });

        jLabel4.setText("链接名称：");

        linkName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sub)
                                .addGap(58, 58, 58)
                                .addComponent(cla))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(period, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(linkName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(linkName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(period, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub)
                    .addComponent(cla))
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void urlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        // TODO add your handling code here:
        String urlVal = url.getText();
        String linkNameVal = linkName.getText();
        long periodVal = Long.valueOf(period.getText());
        Date date = new Date();
        Link link = new Link();
        link.setPeriod(periodVal);
        link.setLinkUrl(urlVal);
        link.setEtime(date.getTime() + periodVal);
        link.setLinkName(linkNameVal);
        link.setId(id);
        LinkService linkService = ctx.getBean("linkService", LinkService.class);
        linkService.updateLink(link);
        JOptionPane.showMessageDialog(this, "更新链接成功");
        GrapFrame frame = (GrapFrame) this.getParent().getParent().getParent().getParent();
        frame.remove(this);
        LinkListPanel llp = new LinkListPanel(ctx);
        frame.replacePanle(llp);
    }//GEN-LAST:event_subActionPerformed

    private void claActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claActionPerformed
        // TODO add your handling code here:
        GrapFrame frame = (GrapFrame) this.getParent().getParent().getParent().getParent();
        frame.remove(this);
        LinkListPanel llp = new LinkListPanel(ctx);
        frame.replacePanle(llp);
    }//GEN-LAST:event_claActionPerformed

    private void linkNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linkNameActionPerformed

    private void initLink(long linkId) {
        LinkService linkService = ctx.getBean("linkService", LinkService.class);
        Link link = linkService.getLinkById(linkId);
        linkName.setText(link.getLinkName());
        period.setText(String.valueOf(link.getPeriod()));
        url.setText(link.getLinkUrl());
        id = link.getId();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField linkName;
    private javax.swing.JTextField period;
    private javax.swing.JButton sub;
    private javax.swing.JTextField url;
    // End of variables declaration//GEN-END:variables
}
