/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package grabjd.panel;

import grabjd.dto.Goods;
import grabjd.service.GoodsService;
import grabjd.table.GoodsTableModel;
import grabjd.table.IconTableCellRenderer;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import org.apache.commons.lang3.math.NumberUtils;
import org.springframework.context.ApplicationContext;

/**
 *
 * @author cz
 */
public class GoodsListPanel extends javax.swing.JPanel {

    private ApplicationContext ac;

    /**
     * Creates new form GoodsListPanel
     */
    public GoodsListPanel(ApplicationContext ac) {
        this.ac = ac;
        initComponents();
        loadData();
    }

    private void loadData() {
        GoodsService goodsService = ac.getBean("goodsService", GoodsService.class);
        List<Goods> goodsList = goodsService.getGoods();
        dataTable.setRowHeight(40);
        GoodsTableModel gtm = new GoodsTableModel(goodsList);
        dataTable.setModel(gtm);
        TableColumn tableColumnId = dataTable.getColumnModel().getColumn(0);
        tableColumnId.setMinWidth(0);
        tableColumnId.setMaxWidth(0);
        tableColumnId.setPreferredWidth(0);
        dataTable.getColumnModel().getColumn(1).setPreferredWidth(400);
        dataTable.getColumnModel().getColumn(2).setPreferredWidth(300);
        dataTable.getColumnModel().getColumn(8).setCellRenderer(new IconTableCellRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        goodsTitle = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        dicountJLabel = new javax.swing.JLabel();
        discountJTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        delGoodsjButton = new javax.swing.JButton();
        javax.swing.JLabel dicountExJLabel = new javax.swing.JLabel();

        dataTable.setAutoCreateRowSorter(true);
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dataTable);

        jLabel1.setText("商品名称：");

        jButton1.setText("查询");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dicountJLabel.setText("折扣率：");

        saveButton.setText("保存");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        delGoodsjButton.setText("删除商品");
        delGoodsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delGoodsjButtonActionPerformed(evt);
            }
        });

        dicountExJLabel.setText("（0.78:78折）");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goodsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(dicountJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dicountExJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delGoodsjButton)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addComponent(goodsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(dicountJLabel)
                        .addComponent(discountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(saveButton)
                        .addComponent(delGoodsjButton))
                    .addComponent(dicountExJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String goodsTitleVal = goodsTitle.getText();
        GoodsService goodsService = ac.getBean("goodsService", GoodsService.class);
        List<Goods> goodsList = goodsService.getlGoods(goodsTitleVal);
        GoodsTableModel GoodsTableModel = (GoodsTableModel) dataTable.getModel();
        GoodsTableModel.setData(goodsList);
        GoodsTableModel.fireTableDataChanged();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String discountText = discountJTextField.getText();
        int[] selectRowsIndex = dataTable.getSelectedRows();
        if (selectRowsIndex.length == 0) {
            JOptionPane.showMessageDialog(this, "请选择要更新的数据!");
        } else {
            if (NumberUtils.isNumber(discountText)) {
                GoodsTableModel goodsTableModel = (GoodsTableModel) dataTable.getModel();
                for (int rowsIndex : selectRowsIndex) {
                    Goods updateGoods = new Goods();
                    String manualPriceStr = (String) goodsTableModel.getValueAt(rowsIndex, 6);
                    String costPriceStr = (String) goodsTableModel.getValueAt(rowsIndex, 3);
                    Long manualPrice = new BigDecimal(manualPriceStr).multiply(new BigDecimal("100")).longValue();
                    Long discountPrice = new BigDecimal(costPriceStr).multiply(new BigDecimal(discountText).multiply(new BigDecimal("100"))).longValue();
                    updateGoods.setId((Long) goodsTableModel.getValueAt(rowsIndex, 0));
                    updateGoods.setDiscountPrice(discountPrice);
                    updateGoods.setManualPrice(manualPrice);
                    updateGoods.setDiffPrice(manualPrice - discountPrice);
                    updateGoods.setDiscountRate(new BigDecimal(discountText).multiply(new BigDecimal("100")).longValue());
                    GoodsService goodsService = ac.getBean("goodsService", GoodsService.class);
                    goodsService.updateAllGoods(updateGoods);
                }
                JOptionPane.showMessageDialog(this, "修改成功!");
                discountJTextField.setText("");
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "折扣率必须为数字！");
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void delGoodsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delGoodsjButtonActionPerformed
        // TODO add your handling code here:
        int[] selectRowsIndex = dataTable.getSelectedRows();
        if (selectRowsIndex.length == 0) {
            JOptionPane.showMessageDialog(this, "请选择要删除的商品");
        } else {
            for (int rowsIndex : selectRowsIndex) {
                GoodsTableModel goodsTableModel = (GoodsTableModel) dataTable.getModel();
                long goodsId = (Long)goodsTableModel.getValueAt(rowsIndex, 0);
                GoodsService goodsService = ac.getBean("goodsService", GoodsService.class);
                goodsService.delGoods(goodsId);
                goodsTableModel.fireTableDataChanged();
            }
            JOptionPane.showMessageDialog(this, "删除成功!");
            loadData();
        }
    }//GEN-LAST:event_delGoodsjButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dataTable;
    private javax.swing.JButton delGoodsjButton;
    private javax.swing.JLabel dicountJLabel;
    private javax.swing.JTextField discountJTextField;
    private javax.swing.JTextField goodsTitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
