/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package grabjd.panel;

import grabjd.GrabFrame;
import grabjd.dto.Link;
import grabjd.service.LinkService;
import grabjd.table.LinkTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import org.springframework.context.ApplicationContext;

/**
 *
 * @author cz
 */
public class LinkListPanel extends javax.swing.JPanel {

    private ApplicationContext ctx;

    /**
     * Creates new form LinkListPanel
     */
    public LinkListPanel(ApplicationContext ctx) {
        this.ctx = ctx;
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        add = new javax.swing.JButton();
        modify = new javax.swing.JButton();
        del = new javax.swing.JButton();

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dataTable);
        dataTable.getColumnModel().getColumn(0).setMinWidth(5);
        dataTable.getColumnModel().getColumn(0).setPreferredWidth(5);
        dataTable.getColumnModel().getColumn(0).setMaxWidth(5);

        add.setText("新增");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        modify.setText("修改");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });

        del.setText("删除");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modify)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(modify)
                    .addComponent(del))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        AddLinkPanel alPanel = new AddLinkPanel(ctx);
        GrabFrame frame = (GrabFrame) this.getParent().getParent().getParent().getParent();
        frame.remove(this);
        frame.replacePanle(alPanel);
    }//GEN-LAST:event_addActionPerformed

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
        // TODO add your handling code here:
        int selectIndex = dataTable.getSelectedRow();
        if (selectIndex == -1) {
            JOptionPane.showMessageDialog(this, "请选择删除列");
        } else {
            long id = (Long) dataTable.getModel().getValueAt(selectIndex, 0);
            ModifyLinkPanel mlPanel = new ModifyLinkPanel(ctx, id);
            GrabFrame frame = (GrabFrame) this.getParent().getParent().getParent().getParent();
            frame.remove(this);
            frame.replacePanle(mlPanel);
        }

    }//GEN-LAST:event_modifyActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        LinkService linkService = ctx.getBean("linkService", LinkService.class);
        int[] selectRows = dataTable.getSelectedRows();
        long[] delids = new long[selectRows.length];
        for (int i = 0; i < delids.length; i++) {
            delids[i] = (Long) dataTable.getModel().getValueAt(selectRows[i], 0);
            linkService.delLink(delids);
        }
        JOptionPane.showMessageDialog(this, "删除成功");
        loadData();
    }//GEN-LAST:event_delActionPerformed

    private void loadData() {
        LinkService linkService = ctx.getBean("linkService", LinkService.class);
        List<Link> linkList = linkService.getLink();
        dataTable.setRowHeight(40);
        dataTable.setModel(new LinkTableModel(linkList));
        dataTable.getColumnModel().getColumn(0).setMinWidth(100);
        dataTable.getColumnModel().getColumn(0).setMaxWidth(100);
        dataTable.getColumnModel().getColumn(0).setPreferredWidth(100);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton del;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modify;
    // End of variables declaration//GEN-END:variables
}
